Repository Rateit-PM4-Org/Rateit, pull requests merged in 2025-03, with the labels that each got.

#23 Feature angular structure and docker
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/src/app/app.component.ts
  frontend/src/app/shared/services/api.service.spec.ts
  frontend/src/app/shared/services/api.service.ts
Labels: technical-frontend, techincal-infrastructure

#66 Feature kubernetes config
  api/src/main/java/ch/zhaw/rateit/api/config/WebConfig.java
  frontend/Dockerfile
  infrastructure/kubernetes/base/api.yaml
  infrastructure/kubernetes/base/configmap.yaml
  infrastructure/kubernetes/base/db.yaml
  infrastructure/kubernetes/base/frontend.yaml
  infrastructure/kubernetes/base/kustomization.yaml
  infrastructure/kubernetes/base/secrets.yaml
Labels: docker

#142 129 readme setupcontribution mit link zu wiki ergänzen
  README.md
Labels: documentation

#157 Update README.md
  README.md
Labels: documentation

#171 170: bugfix actuator endpoints security + mongo upgrade dev-deps
  api/src/main/java/ch/zhaw/rateit/api/config/WebsecurityConfig.java
  infrastructure/docker/docker-compose-dev.yaml
Labels: technical-backend, techincal-infrastructure

#184 Refactor Profile and TabMenu: Ionic-Lifecycle
  frontend/src/app/features/tabs/profile/profile.component.spec.ts
  frontend/src/app/features/tabs/profile/profile.component.ts
  frontend/src/app/features/tabs/tab-menu/tab-menu.component.spec.ts
  frontend/src/app/features/tabs/tab-menu/tab-menu.component.ts
  frontend/src/app/shared/services/user.service.ts
Labels: prio-high

#183 Remove test-related code and update home component title
  api/src/main/java/ch/zhaw/rateit/api/config/WebsecurityConfig.java
  api/src/main/java/ch/zhaw/rateit/api/config/db/migration/RemoveTestsChangelog.java
  api/src/main/java/ch/zhaw/rateit/api/logic/test/TestController.java
  api/src/main/java/ch/zhaw/rateit/api/logic/test/TestEntity.java
  api/src/main/java/ch/zhaw/rateit/api/logic/test/TestEntityRepository.java
  api/src/test/java/ch/zhaw/rateit/api/RateitAPIRequestTest.java
  api/src/test/java/ch/zhaw/rateit/api/config/db/migration/RemoveTestsChangelogTest.java
  api/src/test/java/ch/zhaw/rateit/api/config/ratelimit/RateLimitIntegrationTests.java
  frontend/src/app/features/tabs/home/home.component.html
  frontend/src/app/features/tabs/home/home.component.spec.ts
  frontend/src/app/features/tabs/home/home.component.ts
  frontend/src/app/shared/services/test.service.spec.ts
  frontend/src/app/shared/services/test.service.ts
Labels: prio-low

#179 178-exception-handler-bugfix
  api/src/main/java/ch/zhaw/rateit/api/exceptions/handler/ExceptionHandlers.java
Labels: prio-low
